### ISSUE TITLE
Plugin cannot be installed on cordova-android 6.3.0, but upgrading also fails.

### ISSUE THREAD

**Issue by AndreasGassmann** [chemerisuk/cordova-plugin-firebase-dynamiclinks#13]
If I try to install the plugin in my project, it tells me that I need to upgrade the version of cordova-android.

```
Plugin doesn't support this project's cordova-android version. cordova-android: 6.3.0, failed version requirement: >=7.0.0
Skipping 'cordova-plugin-firebase-dynamiclinks' for android
```

But when I do that, I get the following error:

```
Failed to install 'cordova-plugin-device': Error: ENOENT: no such file or directory, open '/Users/andreas/Programming/app/platforms/android/AndroidManifest.xml'
    at Object.fs.openSync (fs.js:653:18)
    at Object.fs.readFileSync (fs.js:554:33)
    at Object.parseElementtreeSync (/Users/andreas/Programming/app/platforms/android/cordova/node_modules/cordova-common/src/util/xml-helpers.js:180:27)
    at new AndroidManifest (/Users/andreas/Programming/app/platforms/android/cordova/lib/AndroidManifest.js:29:20)
    at AndroidProject.getPackageName (/Users/andreas/Programming/app/platforms/android/cordova/lib/AndroidProject.js:99:12)
    at Api.addPlugin (/Users/andreas/Programming/app/platforms/android/cordova/Api.js:223:57)
    at handleInstall (/Users/andreas/.nvm/versions/node/v8.7.0/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:594:10)
    at /Users/andreas/.nvm/versions/node/v8.7.0/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:357:28
    at _fulfilled (/Users/andreas/.nvm/versions/node/v8.7.0/lib/node_modules/cordova/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/Users/andreas/.nvm/versions/node/v8.7.0/lib/node_modules/cordova/node_modules/q/q.js:816:30)
Error: ENOENT: no such file or directory, open '/Users/andreas/Programming/app/platforms/android/AndroidManifest.xml'
```

I read on stackoverflow that this doesn't necessarily have to do with the AndroidManifest.xml file, but rather some files (like google-services.json) not being found. So I added this to my config.xml as well:

```
<resource-file src="google-services.json" target="google-services.json" />
<preference name="GoogleAndroidClientId" value="google-services.json" />
````

```
<resource-file src="GoogleService-Info.plist" />
<preference name="GoogleIOSClientId" value="GoogleService-Info.plist" />
```

But I'm still getting the same error.

Did anyone else also encounter this error?

**Comment by RafaelAdao** [comment]
I have the same problem.

**Comment by AndreasGassmann** [comment]
@RafaelAdao I ended up using the version from the open pull request and it seems to work fine. https://github.com/chemerisuk/cordova-plugin-firebase-dynamiclinks/pull/10 Would be nice if that could get merged.

**Comment by chemerisuk** [comment]
Version 1 requires `cordova-android 7+`

**Comment by jullicer** [comment]
@AndreasGassmann how did you install using that version ?

**Comment by AndreasGassmann** [comment]
@jullicer You just have to point to his git url `cordova plugin add https://github.com/Chuckv01/cordova-plugin-firebase-dynamiclinks`

**Comment by jullicer** [comment]
@AndreasGassmann Thanks
